CREATE SCHEMA IF NOT EXISTS bungalow;

SET search_path TO bungalow;

CREATE TABLE IF NOT EXISTS person  (
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstName TEXT,
    lastName  TEXT
)